# Generated by Django 2.1.5 on 2019-02-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_roll_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='user',
        ),
    ]
