# Generated by Django 2.1.5 on 2019-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0003_remove_roll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
